galibelle/Controllers/GalibelleController.cs
using galibelle.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace galibelle.Controllers
{
    public class GalibelleController : Controller
    {

        public ActionResult Index()
        {
            if (Session["LogedUserID"] == null) { return RedirectToAction("Login"); }
            else if (Session["LogedUserID"].Equals("1"))
            {
                Session["menu"] = 4;
                return View();
            }

            else
                return RedirectToAction("Sucursal");

        }
        public ActionResult Estadisticas()
        {
            if (Session["LogedUserID"] == null) { return RedirectToAction("Login"); }
            else if (Session["LogedUserID"].Equals("1"))
            {
                Session["menu"] = 7;
                return View();
            }
            else
                return RedirectToAction("Sucursal");
        }

        public ActionResult ListaSucursales()
        {
            if (Session["LogedUserID"] == null) { return RedirectToAction("Login"); }
            else if (Session["LogedUserID"].Equals("1"))
            {
                Session["menu"] = 6;
                var lista = from usu in Utils.GalibelleContext.Usuarios
                            join suc in Utils.GalibelleContext.Sucursales on usu.IdSucursales equals suc.IdSucursales
                            where usu.IdUsuario != 1
                            select new MyViewModel { Usuarios = usu, Sucursales = suc };
                ViewBag.MyViewModel = lista;
                return View();
            }
            else
                return RedirectToAction("Sucursal");
        }
       
        public ActionResult PedidosSucursal(int i)
        {
            if (Session["LogedUserID"] == null) { return RedirectToAction("Login"); }
            else if (Session["LogedUserID"].Equals("1"))
            {
                Session["menu"] = 6;
                var lista = from sto in Utils.GalibelleContext.Stock_suelas
                            join sue in Utils.GalibelleContext.Suelas on sto.IdSuelas equals sue.IdSuelas
                            join mod in Utils.GalibelleContext.Modelos on sue.IdModelos equals mod.IdModelos
                            where sto.IdSucursales == i
                            select new MyViewModel { Stock_suelas = sto, Suelas = sue, Modelos = mod };
                ViewBag.MyViewModel = lista;

                var lista2 = from sto in Utils.GalibelleContext.Stock_straps
                             join str in Utils.GalibelleContext.Straps on sto.IdStraps equals str.IdStraps
                             join mod in Utils.GalibelleContext.Modelos on str.IdModelos equals mod.IdModelos
                             join tip in Utils.GalibelleContext.Tipo_strap on sto.IdTipo_strap equals tip.IdTipo_strap
                             join col in Utils.GalibelleContext.Colores on tip.IdColores equals col.IdColores
                             join text in Utils.GalibelleContext.Textura on tip.IdTextura equals text.IdTextura
                             where sto.IdSucursales == i
                             select new MyViewModel { Stock_straps = sto, Straps = str, Modelos = mod, Colores = col, Textura = text, Tipo_strap = tip };


                ViewBag.MyViewModel2 = lista2;
                return View();
            }
            else
                return RedirectToAction("Sucursal");
        }
        public ActionResult VentasSucursal(int i)
        {
            if (Session["LogedUserID"] == null) { return RedirectToAction("Login"); }
            else if (Session["LogedUserID"].Equals("1"))
            {
                Session["menu"] = 6;
                var lista = from sto in Utils.GalibelleContext.Stock_suelas
                            join sue in Utils.GalibelleContext.Suelas on sto.IdSuelas equals sue.IdSuelas
                            join mod in Utils.GalibelleContext.Modelos on sue.IdModelos equals mod.IdModelos
                            where sto.IdSucursales == i
                            select new MyViewModel { Stock_suelas = sto, Suelas = sue, Modelos = mod };
                ViewBag.MyViewModel = lista;

                var lista2 = from sto in Utils.GalibelleContext.Stock_straps
                             join str in Utils.GalibelleContext.Straps on sto.IdStraps equals str.IdStraps
                             join mod in Utils.GalibelleContext.Modelos on str.IdModelos equals mod.IdModelos
                             join tip in Utils.GalibelleContext.Tipo_strap on sto.IdTipo_strap equals tip.IdTipo_strap
                             join col in Utils.GalibelleContext.Colores on tip.IdColores equals col.IdColores
                             join text in Utils.GalibelleContext.Textura on tip.IdTextura equals text.IdTextura
                             where sto.IdSucursales == i
                             select new MyViewModel { Stock_straps = sto, Straps = str, Modelos = mod, Colores = col, Textura = text, Tipo_strap = tip };


                ViewBag.MyViewModel2 = lista2;
                return View();
            }
            else
                return RedirectToAction("Sucursal");
        }
        public ActionResult EstadisticasSucursal(int i)
        {
            if (Session["LogedUserID"] == null) { return RedirectToAction("Login"); }
            else if (Session["LogedUserID"].Equals("1"))
            {
                Session["menu"] = 6;
                return View();
            }
            else
                return RedirectToAction("Sucursal");
        }

        public ActionResult StockSucursal(int i)
        {

            if (Session["LogedUserID"] == null) { return RedirectToAction("Login"); }
            else if (Session["LogedUserID"].Equals("1"))
            {
                System.Diagnostics.Debug.WriteLine(i);
                Session["menu"] = 6;
                var lista = from sto in Utils.GalibelleContext.Stock_suelas
                            join sue in Utils.GalibelleContext.Suelas on sto.IdSuelas equals sue.IdSuelas
                            join mod in Utils.GalibelleContext.Modelos on sue.IdModelos equals mod.IdModelos
                            where sto.IdSucursales==i
                            select new MyViewModel { Stock_suelas = sto, Suelas = sue, Modelos = mod };
                ViewBag.MyViewModel = lista;

                var lista2 = from sto in Utils.GalibelleContext.Stock_straps
                             join str in Utils.GalibelleContext.Straps on sto.IdStraps equals str.IdStraps
                             join mod in Utils.GalibelleContext.Modelos on str.IdModelos equals mod.IdModelos
                             join tip in Utils.GalibelleContext.Tipo_strap on sto.IdTipo_strap equals tip.IdTipo_strap
                             join col in Utils.GalibelleContext.Colores on tip.IdColores equals col.IdColores
                             join text in Utils.GalibelleContext.Textura on tip.IdTextura equals text.IdTextura
                             where sto.IdSucursales == i
                             select new MyViewModel { Stock_straps = sto, Straps = str, Modelos = mod, Colores = col, Textura = text, Tipo_strap = tip };


                ViewBag.MyViewModel2 = lista2;
                return View();
            }
            else
                return RedirectToAction("Sucursal");
        }

        public ActionResult Straps()
        {

            if (Session["LogedUserID"] == null) { return RedirectToAction("Login"); }
            else if (Session["LogedUserID"].Equals("1")) {
                Session["menu"] = 5;
                var lista = from sto in Utils.GalibelleContext.Stock_straps
                            join str in Utils.GalibelleContext.Straps on sto.IdStraps equals str.IdStraps
                            join mod in Utils.GalibelleContext.Modelos on str.IdModelos equals mod.IdModelos
                            join tip in Utils.GalibelleContext.Tipo_strap on sto.IdTipo_strap equals tip.IdTipo_strap
                            join col in Utils.GalibelleContext.Colores on tip.IdColores equals col.IdColores
                            join text in Utils.GalibelleContext.Textura on tip.IdTextura equals text.IdTextura
                            where sto.IdSucursales==1
                            select new MyViewModel { Stock_straps = sto, Straps = str, Modelos = mod, Colores = col, Textura = text, Tipo_strap = tip };
                ViewBag.MyViewModel=lista;
                return View();
            }
            else
                return RedirectToAction("Sucursal");

        }
        public ActionResult Suelas()
        {
            if (Session["LogedUserID"] == null) { return RedirectToAction("Login"); }
            else if (Session["LogedUserID"].Equals("1"))
            {
                Session["menu"] = 5;

                var lista = from sto in Utils.GalibelleContext.Stock_suelas
                            join sue in Utils.GalibelleContext.Suelas on sto.IdSuelas equals sue.IdSuelas
                            join mod in Utils.GalibelleContext.Modelos on sue.IdModelos equals mod.IdModelos
                            where sto.IdSucursales==1
                            select new MyViewModel { Stock_suelas = sto, Suelas = sue, Modelos = mod};
                ViewBag.MyViewModel = lista;
                return View();


            }
            else
                return RedirectToAction("Sucursal");
        }

        public ActionResult Login() {
            Session.Clear();
            Session.RemoveAll();
            return View();
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Usuarios u) {
            if (ModelState.IsValid) {
                var db = Utils.GalibelleContext;

galibelle/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html style="min-height:100%; position:relative">
<head>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <title>@ViewBag.Title - Galibelle</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap core CSS -->
    <link href="../Content/bootstrap.css" rel="stylesheet">
    <!--external css-->
    <link href="../fonts/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link href="../fonts/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="../Scripts/gritter/css/jquery.gritter.css" />

    <link rel="stylesheet" type="text/css" href="../icon/style.css">

    <!-- Custom styles for this template -->
    <link href="../Content/style.css" rel="stylesheet">
    <link href="../Content/style-responsive.css" rel="stylesheet">

    <script src="../Scripts/chart-master/Chart.js"></script>
    <link rel="icon" type="image/png" href="~/img/logo1.png" />
</head>
<body style="height:100%;">
    <script>
        var contador = 0;
        var menu = 0;
    </script>
    <header class="header black-bg">
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars tooltips" data-placement="right" data-original-title="" onclick="mostrar()"></div>
        </div>
        <!--logo start-->
        <a href='@Url.Action("Index","Galibelle")' class="logo" style="visibility:hidden;" id="nombre"><b>GALIBELLE</b></a>
        <!--logo end-->


        <div class="top-menu">
            <ul class="nav pull-right top-menu">
                <li><a style="font-weight:bold; font-size:14px;" class="logout" href='@Url.Action("Login","Galibelle")'>Salir</a></li>
            </ul>
        </div>
    </header>
        <aside>
            <div id="sidebar" class="nav-collapse " style="z-index:5;">
                <!-- sidebar menu start-->
                <ul class="sidebar-menu" id="nav-accordion" style="margin-top:50%;">
                    <div class="img-circle" style="width:55%; height:27%; background:#ffd777; padding-bottom:8%;padding-top:8%; border:1px solid; border-color:#C79D21; margin:0 auto" ;>
                        <p class="centered"><a href='@Url.Action("Index","Galibelle")'><img style="color:blue; padding-top:15%; padding-bottom:15%;" src="../img/icono.png" width="90"></a></p>
                    </div>
                    <a data-toggle="modal" href="#myModal5"><h5 class="centered">Administrador</h5></a>


                    <li class="mt">
                        <a id="c4" href='@Url.Action("Index","Galibelle")'>
                            <i class="fa fa-star"></i>
                            <span>Inicio</span>
                        </a>
                    </li>

                    <li class="sub-menu">
                        <a id="c5" onclick="noCambiar()">
                            <i class="fa fa-list-alt"></i>
                            <span>Productos</span>
                        </a>
                        <ul class="sub">
                            <li><a onclick="noCambiar()" href='@Url.Action("Straps","Galibelle")'>Straps</a></li> <!--Temporal, falta hacer el mío propio para el almacen-->
                            <li><a onclick="noCambiar()" href='@Url.Action("Suelas","Galibelle")'>Suelas</a></li>
                        </ul>
                    </li>

                    <li class="sub-menu">
                        <a id="c6" href='@Url.Action("ListaSucursales","Galibelle")'>
                            <i class="fa fa-university"></i>
                            <span>Sucursales</span>
                        </a>
                       
                    </li>
                    <li class="sub-menu">
                        <a id="c7" href='@Url.Action("Estadisticas","Galibelle")'>
                            <i class="fa fa-line-chart"></i>
                            <span>Estadísticas</span>
                        </a>

                    </li>



                </ul>
                <!-- sidebar menu end-->
            </div>
        </aside>
        @RenderBody()
</body>

<footer class="site-footer" style="position:absolute; width:100%; bottom:-3%;z-index:3;">
    <div class="text-center">
        2016 - G A L I B E L L E
        <a href="#" class="go-top">
            <i class="fa fa-angle-up"></i>
        </a>
    </div>
</footer>
</html>

<script class="include" type="text/javascript" src="../Scripts/jquery.dcjqaccordion.2.7.js"></script>

<script src="../Scripts/jquery.scrollTo.min.js"></script>
<script src="../Scripts/jquery.nicescroll.js" type="text/javascript"></script>
<script src="../Scripts/jquery.sparkline.js"></script>



<!--common script for all pages-->
<script src="../Scripts/common-scripts.js"></script>


<script type="text/javascript" src="../Scripts/gritter-conf.js"></script>

<!--script for this page-->
<script src="../Scripts/sparkline-chart.js"></script>
<script src="../Scripts/zabuto_calendar.js"></script>



<script type="application/javascript">
    $(document).ready(function () {
        $("#date-popover").popover({html: true, trigger: "manual"});
        $("#date-popover").hide();
        $("#date-popover").click(function (e) {
            $(this).hide();
        });

        $("#my-calendar").zabuto_calendar({
            action: function () {
                return myDateFunction(this.id, false);
            },
            action_nav: function () {
                return myNavFunction(this.id);
            },
            ajax: {
                url: "show_data.php?action=1",
                modal: true
            },
            legend: [
                {type: "text", label: "Special event", badge: "00"},
                {type: "block", label: "Regular event", }
            ]
        });
    });


    function myNavFunction(id) {
        $("#date-popover").hide();
        var nav = $("#" + id).data("navigation");
        var to = $("#" + id).data("to");
        console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
    }
</script>

<!-- Modal  VER-->
<div class="modal fade" id="myModal5" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h2 style="font-weight:bold;" class="modal-title" id="myModalLabel">Datos administrador</h2>
            </div>
            <div class="col-md-12" style="padding:0%;">
                <div class="panel panel-white">

                    <div class="panel-body">
                        <form>

                            <div class="form-group">
                                <label style="color:#3e3939;font-weight:bold;font-size:16px;">Dirección del almacén: </label>
                                <input id="inputDireccion" disabled class="form-control" placeholder="Mar de Japón #17 Fracc. Costa Verde">
                            </div>
                            <div class="form-group">
                                <label style="color:#3e3939;font-weight:bold;font-size:16px;">Teléfono: </label>
                                <input id="inputTel" disabled class="form-control" placeholder="2251006309">
                            </div>
                            <div class="form-group">
                                <label style="color:#3e3939;font-weight:bold;font-size:16px;">Usuario: </label>
                                <input id="inputUsuario" disabled class="form-control" placeholder="Almacén">
                            </div>
                            <div class="form-group">
                                <label style="color:#3e3939;font-weight:bold;font-size:16px;">Contraseña: </label>
                                <input id="inputContras" disabled class="form-control" placeholder="1234567890">
                            </div>
                            <div class="modal-footer">
                                <button id="guardarInput" onclick="guardar()" data-dismiss="modal" style="visibility:hidden;" type="button" class="pull-left btn btn-primary">Guardar cambios</button>
                                <button id="cambiarInput" onclick="cambiar()" type="button" class="pull-right btn btn-primary">Realizar cambios</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><!--END MODAL VER-->
<script type="text/javascript">

    function mostrar() {
        var nombre = document.getElementById('nombre');
        if (contador == 0) {
            nombre.style.visibility = "visible";
            contador = 1;
        }
        else {
            nombre.style.visibility = "hidden";
            contador = 0;
        }
    }
    function cambiar () {
        var Dir = document.getElementById('inputDireccion');
        var Tel = document.getElementById('inputTel');
        var Usuario = document.getElementById('inputUsuario');
        var Contras = document.getElementById('inputContras');
        var guardar = document.getElementById('guardarInput');
        var cambiar = document.getElementById('cambiarInput');

        Dir.disabled = false;
        Tel.disabled = false;
        Usuario.disabled = false;
        Contras.disabled = false;
        guardar.style.visibility = "visible";
        cambiar.style.visibility = "hidden";

    }

    function guardar() {
        var Dir = document.getElementById('inputDireccion');
        var Tel = document.getElementById('inputTel');
        var Usuario = document.getElementById('inputUsuario');
        var Contras = document.getElementById('inputContras');
        var guardar = document.getElementById('guardarInput');
        var cambiar = document.getElementById('cambiarInput');
        Dir.disabled = true;
        Tel.disabled = true;
        Usuario.disabled = true;
        Contras.disabled = true;
        guardar.style.visibility = "hidden";
        cambiar.style.visibility = "visible";
    }
    function noCambiar(){
        
        if(@Session["menu"]==4){
            document.getElementById('c4').style.background="#424a5d";
            document.getElementById('c4').style.color="#aeb2b7";
        }
        if(@Session["menu"]==5){
            document.getElementById('c5').style.background="#424a5d";
            document.getElementById('c5').style.color="#aeb2b7";
        }
        if(@Session["menu"]==6){
            document.getElementById('c6').style.background="#424a5d";
            document.getElementById('c6').style.color="#aeb2b7";
        }
        if(@Session["menu"]==7){
            document.getElementById('c7').style.background="#424a5d";
            document.getElementById('c7').style.color="#aeb2b7";
        }
        document.getElementById("c5").style.background = "#68dff0";
        document.getElementById("c5").style.color = "white";
    }
</script>
<script type="text/javascript">
    window.onload = function () {
        if(@Session["menu"]==4){
            document.getElementById("c4").style.background = "#68dff0";
           document.getElementById("c4").style.color = "white";
        }
        if(@Session["menu"]==5){
            document.getElementById("c5").style.background = "#68dff0";
            document.getElementById("c5").style.color = "white";
        }
        if(@Session["menu"]==6){
            document.getElementById("c6").style.background = "#68dff0";
            document.getElementById("c6").style.color = "white";
        }
        if(@Session["menu"]==7){
            document.getElementById("c7").style.background = "#68dff0";
            document.getElementById("c7").style.color = "white";
        }
    }
</script>